var fakeCoordinatesResponse: String { 
    """
    [
      {
        "name": "London",
        "local_names": {
          "no": "London",
          "ln": "Lóndɛlɛ",
          "si": "ලන්ඩන්",
          "kl": "London",
          "fr": "Londres",
          "ay": "London",
          "ia": "London",
          "sv": "London",
          "gv": "Lunnin",
          "ha": "Landan",
          "hy": "Լոնդոն",
          "tw": "London",
          "hr": "London",
          "bm": "London",
          "ja": "ロンドン",
          "ny": "London",
          "os": "Лондон",
          "tt": "Лондон",
          "av": "Лондон",
          "hu": "London",
          "ba": "Лондон",
          "lt": "Londonas",
          "bi": "London",
          "fj": "Lodoni",
          "so": "London",
          "ky": "Лондон",
          "fy": "Londen",
          "uk": "Лондон",
          "bg": "Лондон",
          "ku": "London",
          "ro": "Londra",
          "tk": "London",
          "kn": "ಲಂಡನ್",
          "lv": "Londona",
          "gn": "Lóndyre",
          "cy": "Llundain",
          "ru": "Лондон",
          "sl": "London",
          "wa": "Londe",
          "br": "Londrez",
          "th": "ลอนดอน",
          "ce": "Лондон",
          "ur": "علاقہ لندن",
          "ps": "لندن",
          "nl": "Londen",
          "io": "London",
          "eo": "Londono",
          "tr": "Londra",
          "feature_name": "London",
          "uz": "London",
          "om": "Landan",
          "yo": "Lọndọnu",
          "pl": "Londyn",
          "ht": "Lonn",
          "sa": "लन्डन्",
          "pa": "ਲੰਡਨ",
          "ascii": "London",
          "qu": "London",
          "es": "Londres",
          "da": "London",
          "az": "London",
          "mk": "Лондон",
          "sq": "Londra",
          "st": "London",
          "na": "London",
          "eu": "Londres",
          "fo": "London",
          "ta": "இலண்டன்",
          "my": "လန်ဒန်မြို့",
          "or": "ଲଣ୍ଡନ",
          "he": "לונדון",
          "vo": "London",
          "nn": "London",
          "kk": "Лондон",
          "zh": "伦敦",
          "sm": "Lonetona",
          "en": "London",
          "li": "Londe",
          "to": "Lonitoni",
          "bn": "লন্ডন",
          "ee": "London",
          "oc": "Londres",
          "wo": "Londar",
          "rm": "Londra",
          "it": "Londra",
          "af": "Londen",
          "tg": "Лондон",
          "tl": "Londres",
          "ar": "لندن",
          "is": "London",
          "sw": "London",
          "et": "London",
          "gd": "Lunnainn",
          "mn": "Лондон",
          "ko": "런던",
          "ab": "Лондон",
          "an": "Londres",
          "mr": "लंडन",
          "ug": "لوندۇن",
          "sr": "Лондон",
          "vi": "Luân Đôn",
          "su": "London",
          "km": "ឡុងដ៍",
          "cv": "Лондон",
          "mt": "Londra",
          "sd": "لنڊن",
          "fi": "Lontoo",
          "mi": "Rānana",
          "gl": "Londres",
          "ms": "London",
          "ga": "Londain",
          "el": "Λονδίνο",
          "zu": "ILondon",
          "bs": "London",
          "bo": "ལོན་ཊོན།",
          "ie": "London",
          "te": "లండన్",
          "co": "Londra",
          "id": "London",
          "de": "London",
          "ml": "ലണ്ടൻ",
          "sh": "London",
          "sk": "Londýn",
          "lb": "London",
          "gu": "લંડન",
          "jv": "London",
          "cu": "Лондонъ",
          "bh": "लंदन",
          "lo": "ລອນດອນ",
          "ka": "ლონდონი",
          "cs": "Londýn",
          "sc": "Londra",
          "fa": "لندن",
          "be": "Лондан",
          "nv": "Tooh Dineʼé Bikin Haalʼá",
          "sn": "London",
          "mg": "Lôndôna",
          "kw": "Loundres",
          "yi": "לאנדאן",
          "ig": "London",
          "hi": "लंदन",
          "pt": "Londres",
          "am": "ለንደን",
          "kv": "Лондон",
          "ne": "लन्डन",
          "ca": "Londres",
          "ff": "London",
          "se": "London"
        },
        "lat": 51.5073219,
        "lon": -0.1276474,
        "country": "GB",
        "state": "England"
      },
      {
        "name": "City of London",
        "local_names": {
          "ru": "Сити",
          "ur": "لندن شہر",
          "uk": "Лондонське Сіті",
          "he": "הסיטי של לונדון",
          "pt": "Cidade de Londres",
          "fr": "Cité de Londres",
          "hi": "सिटी ऑफ़ लंदन",
          "es": "City de Londres",
          "en": "City of London",
          "ko": "시티 오브 런던",
          "lt": "Londono Sitis",
          "zh": "倫敦市"
        },
        "lat": 51.5156177,
        "lon": -0.0919983,
        "country": "GB",
        "state": "England"
      },
      {
        "name": "London",
        "local_names": {
          "iu": "ᓚᓐᑕᓐ",
          "th": "ลอนดอน",
          "el": "Λόντον",
          "ar": "لندن",
          "ko": "런던",
          "ka": "ლონდონი",
          "cr": "ᓬᐊᐣᑕᐣ",
          "be": "Лондан",
          "hy": "Լոնտոն",
          "yi": "לאנדאן",
          "lv": "Landona",
          "fa": "لندن",
          "bn": "লন্ডন",
          "ru": "Лондон",
          "ja": "ロンドン",
          "fr": "London",
          "en": "London",
          "he": "לונדון",
          "lt": "Londonas",
          "ga": "Londain",
          "oj": "Baketigweyaang",
          "ug": "لوندۇن"
        },
        "lat": 42.9832406,
        "lon": -81.243372,
        "country": "CA",
        "state": "Ontario"
      },
      {
        "name": "Chelsea",
        "local_names": {
          "pt": "Chelsea",
          "ar": "تشيلسي",
          "no": "Chelsea",
          "ru": "Челси",
          "vi": "Chelsea, Luân Đôn",
          "tr": "Chelsea, Londra",
          "fr": "Chelsea",
          "sh": "Chelsea, London",
          "hi": "चेल्सी, लंदन",
          "he": "צ'לסי",
          "hu": "Chelsea",
          "da": "Chelsea",
          "ko": "첼시",
          "az": "Çelsi",
          "en": "Chelsea",
          "el": "Τσέλσι",
          "uk": "Челсі",
          "ga": "Chelsea",
          "id": "Chelsea, London",
          "et": "Chelsea",
          "it": "Chelsea",
          "ja": "チェルシー",
          "ur": "چیلسی، لندن",
          "es": "Chelsea",
          "sk": "Chelsea",
          "pl": "Chelsea",
          "sv": "Chelsea, London",
          "eu": "Chelsea",
          "de": "Chelsea",
          "nl": "Chelsea",
          "fa": "چلسی",
          "af": "Chelsea, Londen",
          "zh": "車路士"
        },
        "lat": 51.4875167,
        "lon": -0.1687007,
        "country": "GB",
        "state": "England"
      },
      {
        "name": "London",
        "lat": 37.1289771,
        "lon": -84.0832646,
        "country": "US",
        "state": "Kentucky"
      }
    ]
    """
}
